//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalTreatment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICALCLAIMFORMDETAIL
    {
        public decimal MEDICALCLAIMFORMID { get; set; }
        public decimal ID { get; set; }
        public int SERVICEFEESTYPEID { get; set; }
        public decimal AMOUNT { get; set; }
        public int UNITID { get; set; }
        public decimal NUMBEROFUNITS { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal ENTITLEMENTPERCENT { get; set; }
        public decimal ENTITLEMENTAMOUNT { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
        public Nullable<decimal> APPROVEDAMOUNTDD { get; set; }
    
        public virtual MEDICALCLAIMFORM MEDICALCLAIMFORM { get; set; }
        public virtual SERVICEFEESTYPE SERVICEFEESTYPE { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
