//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalTreatment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD
    {
        public int ID { get; set; }
        public int CARDNUMBER { get; set; }
        public int INDIVIDUALID { get; set; }
        public System.DateTime ISSUEDATE { get; set; }
        public System.DateTime EXPIRYDATE { get; set; }
        public string NOTE { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<short> PRINTCOUNT { get; set; }
        public string STATUS { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
    
        public virtual INDIVIDUAL INDIVIDUAL { get; set; }
    }
}
