//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalTreatment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDIVIDUAL
    {
        public INDIVIDUAL()
        {
            this.CARDS = new HashSet<CARD>();
            this.INDIVIDUALS1 = new HashSet<INDIVIDUAL>();
            this.MEDICALCLAIMFORMs = new HashSet<MEDICALCLAIMFORM>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string NAMEEN { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string GENDER { get; set; }
        public int MAINORGANISATIONID { get; set; }
        public int ORGANISATIONID { get; set; }
        public Nullable<int> DEPARTMENTID { get; set; }
        public Nullable<int> SECTIONID { get; set; }
        public string MARITALSTATUS { get; set; }
        public int RELATIONID { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<int> MAININDIVIDUALID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> TERMINATEDATE { get; set; }
        public Nullable<decimal> YEARLYCEILING { get; set; }
        public Nullable<int> OCCUPATIONID { get; set; }
        public string JOBNUMBER { get; set; }
        public byte[] PHOTO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
        public Nullable<int> JOBTITLEID { get; set; }
    
        public virtual ICollection<CARD> CARDS { get; set; }
        public virtual JOBTITLE JOBTITLE { get; set; }
        public virtual OCCUPATION OCCUPATION { get; set; }
        public virtual ICollection<INDIVIDUAL> INDIVIDUALS1 { get; set; }
        public virtual INDIVIDUAL INDIVIDUAL1 { get; set; }
        public virtual ORGANIZATIONSTRUCTURE ORGANIZATIONSTRUCTURE { get; set; }
        public virtual ORGANIZATIONSTRUCTURE ORGANIZATIONSTRUCTURE1 { get; set; }
        public virtual ORGANIZATIONSTRUCTURE ORGANIZATIONSTRUCTURE2 { get; set; }
        public virtual ORGANIZATIONSTRUCTURE ORGANIZATIONSTRUCTURE3 { get; set; }
        public virtual RELATION RELATION { get; set; }
        public virtual ICollection<MEDICALCLAIMFORM> MEDICALCLAIMFORMs { get; set; }
    }
}
