//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalTreatment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICALSERVICECEILING
    {
        public int ID { get; set; }
        public int MEDICALSERVICEID { get; set; }
        public Nullable<int> MEDICALDETAILSERVICEID { get; set; }
        public short YEAR { get; set; }
        public decimal CEILING { get; set; }
        public string STATUS { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
    
        public virtual MEDICALDETAILSERVICE MEDICALDETAILSERVICE { get; set; }
        public virtual MEDICALSERVICE MEDICALSERVICE { get; set; }
    }
}
