//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalTreatment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICALSERVICE
    {
        public MEDICALSERVICE()
        {
            this.MEDICALCLAIMFORMs = new HashSet<MEDICALCLAIMFORM>();
            this.MEDICALDETAILSERVICES = new HashSet<MEDICALDETAILSERVICE>();
            this.MEDICALSERVICECEILINGs = new HashSet<MEDICALSERVICECEILING>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string NAMEEN { get; set; }
        public string SERVICEINCLUDE { get; set; }
        public string APPLICABLEFOR { get; set; }
        public string CEILINGTYPE { get; set; }
        public string LIMITSERVICE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
    
        public virtual ICollection<MEDICALCLAIMFORM> MEDICALCLAIMFORMs { get; set; }
        public virtual ICollection<MEDICALDETAILSERVICE> MEDICALDETAILSERVICES { get; set; }
        public virtual ICollection<MEDICALSERVICECEILING> MEDICALSERVICECEILINGs { get; set; }
    }
}
